
import { createContext } from 'react'

const Data=createContext()
const data={
    bollywood:{
      post1:{
        img:'https://m.media-amazon.com/images/M/MV5BNTkyOGVjMGEtNmQzZi00NzFlLTlhOWQtODYyMDc2ZGJmYzFhXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_.jpg',
        name:'3 Idiots',
        para:`3 Idiots (stylized as "3 idiots") is a 2009 Indian Hindi-language coming-of-age comedy-drama film written, edited and directed by Rajkumar Hirani, co-written by Abhijat Joshi and produced by Vidhu Vinod Chopra. Adapted loosely from Chetan Bhagat's novel Five Point Someone,[5] the film stars Aamir Khan, R. Madhavan and Sharman Joshi in the titular roles, marking their reunion three years after Rang De Basanti (2006), while Kareena Kapoor, Boman Irani and Omi Vaidya star in pivotal roles. Narrated through two parallel dramas, one in the present and the other set ten years in the past, the story follows the friendship of three students at an Indian engineering college and is a satire about the social pressures under the Indian education system.Produced by Chopra under the banner Vinod Chopra Films,[9][10] 3 Idiots incorporated real Indian inventions created by Remya Jose,[11] Mohammad Idris,[12] Jahangir Painter[13] and Sonam Wangchuk, the latter of whom also inspired Khan's characterUpon its release on December 25, 2009, 3 Idiots received widespread critical acclaim and commercial success and is considered to be among the greatest Bollywood films ever made;[15] it was also the highest-grossing film in its opening weekend in India, had the highest opening day collections for an Indian film up until that point, and also held the record for the highest net collections in the first week for a Hindi film. Eventually, it became one of the few Indian films at the time to become successful in East Asian markets such as China[16] and Japan,[17] eventually bringing its worldwide gross to ₹392 crore ($90 million)[a][18][19] — it was the highest-grossing Indian film ever at the time and the highest grossing Indian film of the 2000s. It is also the 17th highest grossing Indian film of all time.[20] The film also had a social impact on attitudes toward education in India,[21] as well as in other Asian countries such as China.[7]At the 57th National Film Awards, 3 Idiots won 3 National Film Awards, including Best Popular Film Providing Wholesome Entertainment. Additionally, the film received 11 nominations at the 55th Filmfare Awards, including Best Actor (Khan), Best Actress (Kapoor) and Best Supporting Actor (Madhavan and Joshi), and won a leading 6 awards (tying with Dev.D), including Best Film, Best Director (Hirani) and Best Supporting Actor (Irani). Overseas, it won the Grand Prize at Japan's Videoyasan Awards,[22][23][17] while it was nominated for Best Outstanding Foreign Language Film at the Japan Academy Awards[24][25] and Best Foreign Film at China's Beijing International Film Festival.[26]The film was remade in Tamil as Nanban (2012), which also received critical praise and commercial success.[27][28] A Mexican remake, 3 Idiotas, was also released in 2017.[29]`
      },
      post2:{
        img:'https://m.media-amazon.com/images/M/MV5BM2QzM2JiNTMtYjU4Ny00MDZkLTk3MmUtYTRjMzVkZGJlNmYyXkEyXkFqcGdeQXVyMTUzNTgzNzM0._V1_FMjpg_UX1000_.jpg',
        name:'pathaan',
        para:`Pathaan is a 2023 Indian Hindi-language action thriller film directed by Siddharth Anand and produced by Aditya Chopra of Yash Raj Films.[4] The fourth installment in the YRF Spy Universe, it stars Shah Rukh Khan, Deepika Padukone, and John Abraham, alongside Dimple Kapadia and Ashutosh Rana. Written by Shridhar Raghavan and Abbas Tyrewala from a story by Anand, the film is about Pathaan, an exiled RAW agent, who must work with ISI agent Rubina to take down Jim, a former RAW agent-turned-traitor, who is planning to spread a deadly lab-generated virus across India.The film was shot over various locations in India, Afghanistan, Spain, UAE, Turkey, Russia, Italy and France. Grossing ₹877.45 crore (US$110 million) worldwide, Pathaan ranks as the highest-grossing Hindi film of 2023, the fourth-highest-grossing Hindi film and seventh-highest-grossing Indian film of all time, as well as the highest-grossing of Khan's career and Yash Raj Films' releases.`
      },
      post3:{
        img:'https://m.media-amazon.com/images/M/MV5BMTg5NzIzMzEyOF5BMl5BanBnXkFtZTgwMjgzMTg0MzE@._V1_.jpg',
        name:'PK',
        para:`PK (transl. Tipsy) is a 2014 Indian Hindi-language science-fiction comedy-drama film[5][6][7][8] edited and directed by Rajkumar Hirani and written by Hirani and Abhijat Joshi, and jointly produced by Hirani and Vidhu Vinod Chopra under the banners Rajkumar Hirani Films and Vinod Chopra Films respectively. The plot follows an innocent alien (Aamir Khan) who lands on Earth but loses his communication device. He meets Jaggu (Anushka Sharma), a heartbroken reporter, and tries to find his device. With time, he raises many thought-provoking questions.PK was released on 19 December 2014. Upon release, it received positive reviews, with praise directed towards Khan's performance and the film's humour. PK was the first Indian film to gross more than ₹7 billion and US$100 million worldwide. At the time of its release, it emerged as the highest-grossing Indian film of all time. The film's final worldwide gross was ₹769.89 crore (US$118.92 million). `
      }
      
    },
    travel:{
        post1:{
            img:'https://cms-b-assets.familysearch.org/dims4/default/92f0f61/2147483647/strip/true/crop/750x500+0+0/resize/1240x827!/quality/90/?url=https%3A%2F%2Ffamilysearch-brightspot.s3.amazonaws.com%2Fcb%2F2b%2Fab7608ce1f477c824c31846ed2f3%2Feiffel-tower-sunrise.jpg',
            name:'Paris',
            para:`Paris (French pronunciation: ​[paʁi] (listen)) is the capital and most populous city of France, with an estimated population of 2,165,423 residents in 2019 in an area of more than 105 km² (41 sq mi),[5] making it the 30th most densely populated city in the world in 2020.[6] Since the 17th century, Paris has been one of the world's major centres of finance, diplomacy, commerce, fashion, gastronomy, and science. For its leading role in the arts and sciences, as well as its very early system of street lighting, in the 19th century it became known as "the City of Light".[7] Like London, prior to the Second World War, it was also sometimes called the capital of the world.The ancient oppidum that corresponds to the modern city of Paris was first mentioned in the mid-1st century BC by Julius Caesar as Luteciam Parisiorum ('Lutetia of the Parisii'), and is later attested as Parision in the 5th century AD, then as Paris in 1265.[17][18] During the Roman period, it was commonly known as Lutetia or Lutecia in Latin, and as Leukotekía in Greek, which is interpreted as either stemming from the Celtic root *lukot- ('mouse'), or from *luto- ('marsh, swamp'), depending on whether the Latin or Greek form is the closest to the original Gaulish name.At the beginning of the twentieth century, Paris was the largest Catholic city in the world.[177] French census data does not contain information about religious affiliation.[178] According to a 2011 survey by the Institut français d'opinion publique (IFOP), a French public opinion research organisation, 61 percent of residents of the Paris Region (Île-de-France) identified themselves as Roman Catholic. In the same survey, 7 percent of residents identified themselves as Muslims, 4 percent as Protestants, 2 percent as Jewish and 25 percent as without religion.`
          },
          post2:{
            img: "https://www.travelandleisure.com/thmb/6rAXu2YdK34P4bZmmkC6KRTm92c=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/mother-son-maldives-vacation-MALDIVEMISS0820-aecf8960655243e8b0ef311082a92729.jpg",
            name:'Maldives',
            para:`the Maldives (Dhivehi: ދިވެހިރާއްޖެ Dhivehi Raajje) are an archipelago of 1,192 coral islands grouped into 26 coral atolls (200 inhabited islands and 154 islands with tourist resorts) in the Indian Ocean. They lie south-southwest of India and are considered part of Southern Asia.Tourism, Maldives largest industry, accounts for 28% of GDP and more than 60% of the Maldives' foreign exchange receipts. Over 90% of government tax revenue comes from import duties and tourism-related taxes. Over 1.7 million tourists visited the islands in 2019. Fishing is the second leading sector. `
          },
          post3:{
            img:'https://lp-cms-production.imgix.net/features/2017/09/dubai-marina-skyline-2c8f1708f2a1.jpg?auto=format&q=75&w=3840',
            name:'Dubai',
            para:`Dubai (/duːˈbaɪ/, doo-BY; Arabic: دبي, romanized: Dubayy, IPA: [dʊˈbajj], Gulf Arabic pronunciation: [dəˈbaj]) is the most populous city in the United Arab Emirates (UAE) and the capital of the Emirate of Dubai, the most populated of the 7 emirates of the United Arab Emirates.[7][8][9] Established in the 18th century as a small fishing village, the city grew rapidly in the early 21st century with a focus on tourism and luxury,[10] having the second most five-star hotels in the world,[11] and the tallest building in the world, the Burj Khalifa, which is 828 metres (2,717 ft) tall.The history of human settlement in the area now defined by the United Arab Emirates is rich and complex, and points to extensive trading links between the civilisations of the Indus Valley and Mesopotamia, but also as far afield as the Levant.[24] Archaeological finds in the emirate of Dubai, particularly at Al-Ashoosh, Al Sufouh and the notably rich trove from Saruq Al Hadid[25] show settlement through the Ubaid and Hafit periods, the Umm Al Nar and Wadi Suq periods and the three Iron Ages in the UAE. The area was known to the Sumerians as Magan, and was a source for metallic goods, notably copper and bronze.Dubai is thought to have been established as a fishing village in the early 18th century[30] and was, by 1822, a town of some 700–800 members of the Bani Yas tribe and subject to the rule of Sheikh Tahnun bin Shakhbut of Abu Dhabi.[31] In 1822, a British naval surveyor noted that Dubai was at that time populated with a thousand people living in an oval-shaped town surrounded by a mud wall, scattered with goats and camels. The main footpath out of the village led to a reedy creek while another trailed off into the desert which merged into caravan routes.`
          }
    }, technology:{
        post1:{
            img:'https://play-lh.googleusercontent.com/RslBy1o2NEBYUdRjQtUqLbN-ZM2hpks1mHPMiHMrpAuLqxeBPcFSAjo65nQHbTA53YYn',
            name:'HTML',
            para:'The HyperText Markup Language or HTML is the standard markup language for documents designed to be displayed in a web browser. It can be assisted by technologies such as Cascading Style Sheets (CSS) and scripting languages such as JavaScriWeb browsers receive HTML documents from a web server or from local storage and render the documents into multimedia web pages. HTML describes the structure of a web page semantically and originally included cues for the appearance of the document.HTML elements are the building blocks of HTML pages. With HTML constructs, images and other objects such as interactive forms may be embedded into the rendered page. HTML provides a means to create structured documents by denoting structural semantics for text such as headings, paragraphs, lists, links, quotes, and other items. HTML elements are delineated by tags, written using angle brackets. Tags such as <img /> and <input /> directly introduce content into the page. Other tags such as <p> surround and provide information about document text and may include other tags as sub-elements. Browsers do not display the HTML tags but use them to interpret the content of the page.HTML can embed programs written in a scripting language such as JavaScript, which affects the behavior and content of web pages. The inclusion of CSS defines the look and layout of content. The World Wide Web Consortium (W3C), former maintainer of the HTML and current maintainer of the CSS standards, has encouraged the use of CSS over explicit presentational HTML since 1997.[2] A form of HTML, known as HTML5, is used to display video and audio, primarily using the <canvas> element, in collaboration with JavaScript.  '
          },
          post2:{
            img: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d5/CSS3_logo_and_wordmark.svg/800px-CSS3_logo_and_wordmark.svg.png",
            name:'CSS',
            para:' Cascading Style Sheets (CSS) is a style sheet language used for describing the presentation of a document written in a markup language such as HTML or XML (including XML dialects such as SVG, MathML or XHTML).[1] CSS is a cornerstone technology of the World Wide Web, alongside HTML and JavaScript.CSS is designed to enable the separation of content and presentation, including layout, colors, and fonts.[3] This separation can improve content accessibility; provide more flexibility and control in the specification of presentation characteristics; enable multiple web pages to share formatting by specifying the relevant CSS in a separate .css file, which reduces complexity and repetition in the structural content; and enable the .css file to be cached to improve the page load speed between the pages that share the file and its formatting.Separation of formatting and content also makes it feasible to present the same markup page in different styles for different rendering methods, such as on-screen, in print, by voice (via speech-based browser or screen reader), and on Braille-based tactile devices. CSS also has rules for alternate formatting if the content is accessed on a mobile device.[4]The name cascading comes from the specified priority scheme to determine which style rule applies if more than one rule matches a particular element. This cascading priority scheme is predictable.The CSS specifications are maintained by the World Wide Web Consortium (W3C). Internet media type (MIME type) text/css is registered for use with CSS by RFC 2318 (March 1998). The W3C operates a free CSS validation service for CSS documents.[5] In addition to HTML, other markup languages support the use of CSS including XHTML, plain XML, SVG, and XUL.'
          },
          post3:{
            img:'https://upload.wikimedia.org/wikipedia/commons/6/6a/JavaScript-logo.png',
            name:'JavaScipt',
            para:' JavaScript often abbreviated as JS, is a programming language that is one of the core technologies of the World Wide Web, alongside HTML and CSS. As of 2022, 98% of websites use JavaScript on the client side for webpage behavior, often incorporating third-party libraries. All major web browsers have a dedicated JavaScript engine to execute the code on users devicJavaScript is a high-level, often just-in-time compiled language that conforms to the ECMAScript standard.[10] It has dynamic typing, prototype-based object-orientation, and first-class functions. It is multi-paradigm, supporting event-driven, functional, and imperative programming styles. It has application programming interfaces (APIs) for working with text, dates, regular expressions, standard data structures, and the Document Object Model (DOM). The ECMAScript standard does not include any input/output (I/O), such as networking, storage, or graphics facilities. In practice, the web browser or other runtime system provides JavaScript APIs for I/O. JavaScript engines were originally used only in web browsers, but are now core components of some servers and a variety of applications. The most popular runtime system for this usage is Node.js. Although Java and JavaScript are similar in name, syntax, and respective standard libraries, the two languages are distinct and differ greatly in '
          }
    },
    hollywood:{
      post1:{
        img:"https://gumlet.assettype.com/film-companion/import/wp-content/uploads/2020/07/Inception_Lead_4-1.jpg?w=1200&h=675&auto=format%2Ccompress&fit=max&enlarge=true",
        name:'Inception',
        para:`Inception is a 2010 science fiction action film[4][5][6] written and directed by Christopher Nolan, who also produced the film with Emma Thomas, his wife. The film stars Leonardo DiCaprio as a professional thief who steals information by infiltrating the subconscious of his targets. He is offered a chance to have his criminal history erased as payment for the implantation of another person's idea into a target's subconscious.[7] The ensemble cast includes Ken Watanabe, Joseph Gordon-Levitt, Marion Cotillard, Elliot Page,[a] Tom Hardy, Dileep Rao, Cillian Murphy, Tom Berenger, and Michael Caine.

        After the 2002 completion of Insomnia, Nolan presented to Warner Bros. a written 80-page treatment for a horror film envisioning "dream stealers," based on lucid dreaming.[8] Deciding he needed more experience before tackling a production of this magnitude and complexity, Nolan shelved the project and instead worked on 2005's Batman Begins, 2006's The Prestige, and The Dark Knight in 2008.[9] The treatment was revised over 6 months and was purchased by Warner in February 2009.[10] Inception was filmed in six countries, beginning in Tokyo on June 19 and ending in Canada on November 22.[11] Its official budget was $160 million, split between Warner Bros. and Legendary.[12] Nolan's reputation and success with The Dark Knight helped secure the film's US$100 million in advertising expenditure.`
      },
      post2:{
        img: "https://media1.popsugar-assets.com/files/thumbor/0vXx8ApJO0v1KfcMWyGAnMmc82M/fit-in/1200x630/filters:format_auto-!!-:strip_icc-!!-:fill-!white!-/2019/03/25/801/n/1922283/891e0fb65c991a8ee70236.09504101_.jpg",
        name:'Avengers',
        para:`Avengers: Endgame is a 2019 American superhero film based on the Marvel Comics superhero team the Avengers. Produced by Marvel Studios and distributed by Walt Disney Studios Motion Pictures, it is the direct sequel to Avengers: Infinity War (2018) and the 22nd film in the Marvel Cinematic Universe (MCU). Directed by Anthony and Joe Russo and written by Christopher Markus and Stephen McFeely.The film was announced in October 2014 as Avengers: Infinity War – Part 2, but Marvel later removed this title. The Russo brothers joined as directors in April 2015, with Markus and McFeely signing on to write the script a month later. The film serves as a conclusion to the story of the MCU up to that point, ending the story arcs for several main characters.Avengers: Endgame premiered in Los Angeles on April 22, 2019, and was released in the United States on April 26, as part of Phase Three of the MCU. The film received praise for its direction, acting, musical score, action sequences, visual effects, and emotional weight, with critics lauding its culmination of the 22-film story. The film grossed $2.798 billion worldwide, surpassing Infinity War's entire theatrical run in just eleven days and breaking numerous box office records, including becoming the highest-grossing film of all time from July 2019 until March 2021.`
      },
      post3:{
        img:'https://images.hindustantimes.com/img/2022/04/28/1600x900/Avatar_2_1651132982030_1651132999201.webp',
        name:'Avatar',
        para:`Avatar (marketed as James Cameron's Avatar) is a 2009 epic science fiction film directed, written, co-produced, and co-edited by James Cameron and starring Sam Worthington, Zoe Saldana, Stephen Lang, Michelle Rodriguez,[6] and Sigourney Weaver. It is set in the mid-22nd century, when humans are colonizing Pandora, a lush habitable moon of a gas giant in the Alpha Centauri star system, in order to mine the valuable mineral unobtanium.[a] The expansion of the mining colony threatens the continued existence of a local tribe of Na'vi, a humanoid species indigenous to Pandora. The title of the film refers to a genetically engineered Na'vi body operated from the brain of a remotely located human that is used to interact with the natives of Pandora.[10]

        Development of Avatar began in 1994, when James Cameron wrote an 80-page treatment for the film.[11][12] Filming was supposed to take place after the completion of Cameron's 1997 film Titanic, for a planned release in 1999;[13] however, according to Cameron, the necessary technology was not yet available to achieve his vision of the film.In 1994,[12] director James Cameron wrote an 80-page treatment for Avatar, drawing inspiration from "every single science fiction book" he had read in his childhood as well as from adventure novels by Edgar Rice Burroughs and H. Rider Haggard.[11] In August 1996, Cameron announced that after completing Titanic, he would film Avatar, which would make use of synthetic, or computer-generated, actors.[14] The project would cost $100 million and involve at least six actors in leading roles "who appear to be real but do not exist in the physical world".[51] Visual effects house Digital Domain, with whom Cameron has a partnership, joined the project, which was supposed to begin production in mid-1997 for a 1999 release.[13] However, Cameron felt that the technology had not caught up with the story and vision that he intended to tell.`
      }
    },
    fitness:{
      post1:{
        img:"https://www.pulse8gym.com/wp-content/uploads/2021/02/muscles-boy.png",
        name:'GYM',
        para:`A gymnasium, also known as a gym, is an indoor location for athletics. The word is derived from the ancient Greek term "gymnasium".[1] They are commonly found in athletic and fitness centers, and as activity and learning spaces in educational institutions. "Gym" is also slang for "fitness centre", which is often an area for indoor recreation. A "gym" may include or describe adjacent open air areas as well. In Western countries, "gyms" (or pl: gymnasia") often describe places with indoor or outdoor courts for basketball, hockey, tennis, boxing or wrestling, and with equipment and machines used for physical development training, or to do exercises. In many European countries, Gymnasium (and variations of the word) also can describe a secondary school that prepares students for higher education at a university, with or without the presence of athletic courts, fields, or equipment. `
      },
      post2:{
        img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT9MJYSLmTZmMd626GD_nG3tzSGVqnkzXh2eQ&usqp=CAU",
        name:'YOGA',
        para:`Yoga-like practices are first mentioned in the Rigveda.[9] Yoga is referred to in a number of the Upanishads.[10][11][12] The first known appearance of the word "yoga" with the same meaning as the modern term is in the Katha Upanishad,[13][14] which was probably composed between the fifth and third centuries BCE.[15][16] Yoga continued to develop as a systematic study and practice during the fifth and sixth centuries BCE in ancient India's ascetic and Śramaṇa movements.[17] The most comprehensive text on Yoga, the Yoga Sutras of Patanjali, date to the early centuries of the Common Era;[18][19][note 1] Yoga philosophy became known as one of the six orthodox philosophical schools (Darśanas) of Hinduism in the second half of the first millennium CE.[20][web 1] Hatha yoga texts began to emerge between the ninth and 11th centuries, originating in tantra.`
      },
      post3:{
        img:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRjwvT1eQSqznM3HqV2XwaM4sD93XLG-A1-lw&usqp=CAU',
        name:'Meditation',
        para:`Meditation is a practice in which an individual uses a technique – such as mindfulness, or focusing the mind on a particular object, thought, or activity – to train attention and awareness, and achieve a mentally clear and emotionally calm and stable state.[1][2][3][4][web 1][web 2]

        Meditation is practiced in numerous religious traditions. The earliest records of meditation (dhyana) are found in the Upanishads, and meditation plays a salient role in the contemplative repertoire of Jainism, Buddhism and Hinduism.[5] Since the 19th century, Asian meditative techniques have spread to other cultures where they have also found application in non-spiritual contexts, such as business and health.`
      }
    },
    food:{
      post1:{
        img:"https://www.holidify.com/images/cmsuploads/compressed/c700x420_20181227132950.jpg",
        name:'Sushi (Japan)',
        para:'Prepared with vinegared rice and a wide range of ingredients including seafood, vegetables, and sometimes fruits. Sushi tastes best when served with wasabi, pickled ginger, and soy sauce. A popular garnish for this dish is Daikon radish. The type of fish in it defines a sushis taste. However, the vinegared rice gives the dish a tangy taste overall. Tuna, eel, and Salmon tend to have a light flavour while octopus flavoured sushi is generally strong in taste.'
      },
      post2:{
        img: "https://www.holidify.com/images/cmsuploads/compressed/shoyu-ramen_20181227133143.jpg",
        name:'Ramen (Japan) ',
        para:`If not tried, you must have heard of Ramen at least once in your life. However, we are not talking about the packaged instant noodles. Ramen is a Japanese dish made of wheat noodles and served in the broth along with vegetables and meat. Ramen comes in several flavours, from tangy to spicy, depending on the flavour of the broth. Every region in Japan has it's own. Tonkotsu, a popular style of ramen includes pork bone broth and the miso ramen, another popular dish originated in Hokkaido.`
      },
      post3:{
        img:'https://www.holidify.com/images/cmsuploads/compressed/bacon-kebabs-13-2_20181227133457.jpg',
        name:'Kebab (Turkey)',
        para:`A dish popular across the Middle East, Kebabs are originally from Turkey. They consist of ground meat or seafood, fruits, and vegetables in some cases and are cooked on a skewer with a big fire underneath, just like a barbeque on the grill. It is cooked with various accompanying ingredients including garlic, black pepper, and vegetable oil. Mutton or lambs are generally the traditional meats used in kebabs. Other recipes include beef, goat, fish, and chicken as well. This dish has a perfect blend of taste, ranging from tangy to spicy, making it one of the best dishes in the world.`
      }
    }
  }

  export {Data,data}